name: build
on:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm run deploy

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: build.tgz
