name: deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm run deploy

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy
        uses: actions/deploy-pages@v3
